targets:
  $default:
    builders:
      slang_build_runner:
        options:
          input_directory: lib/l10n
          output_directory: lib/l10n
          input_file_pattern: .json
          base_locale: zh-Hant-TW
          fallback_strategy: base_locale
          key_case: camel
          key_map_case: camel
          translate_var: app
          class_name: AppLocalizations
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true