// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNF_8OFHvFgpKnKDfFnPR-2Cq_QobC08c',
    appId: '1:183269888565:web:cf62919976d5be3973577c',
    messagingSenderId: '183269888565',
    projectId: 'nsysu-ap',
    authDomain: 'nsysu-ap.firebaseapp.com',
    databaseURL: 'https://nsysu-ap.firebaseio.com',
    storageBucket: 'nsysu-ap.appspot.com',
    measurementId: 'G-VTVKDLED5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmXUc5FHsF21XdAnAp638LWSs9eBy4OM',
    appId: '1:183269888565:android:b4a03bfcd6375025',
    messagingSenderId: '183269888565',
    projectId: 'nsysu-ap',
    databaseURL: 'https://nsysu-ap.firebaseio.com',
    storageBucket: 'nsysu-ap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8TG7zHXTzd_hmMx6xE_FccYqH_CIQX40',
    appId: '1:183269888565:ios:b4a03bfcd6375025',
    messagingSenderId: '183269888565',
    projectId: 'nsysu-ap',
    databaseURL: 'https://nsysu-ap.firebaseio.com',
    storageBucket: 'nsysu-ap.appspot.com',
    androidClientId: '183269888565-c75gilrrkiiv8dt3pgnnubreget7f4im.apps.googleusercontent.com',
    iosClientId: '183269888565-70pb0kkietf205lp5h45eicn50u0u641.apps.googleusercontent.com',
    iosBundleId: 'com.nsysu.ap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8TG7zHXTzd_hmMx6xE_FccYqH_CIQX40',
    appId: '1:183269888565:ios:b4a03bfcd6375025',
    messagingSenderId: '183269888565',
    projectId: 'nsysu-ap',
    databaseURL: 'https://nsysu-ap.firebaseio.com',
    storageBucket: 'nsysu-ap.appspot.com',
    androidClientId: '183269888565-c75gilrrkiiv8dt3pgnnubreget7f4im.apps.googleusercontent.com',
    iosClientId: '183269888565-70pb0kkietf205lp5h45eicn50u0u641.apps.googleusercontent.com',
    iosBundleId: 'com.nsysu.ap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNF_8OFHvFgpKnKDfFnPR-2Cq_QobC08c',
    appId: '1:183269888565:web:3887a9bb060e528073577c',
    messagingSenderId: '183269888565',
    projectId: 'nsysu-ap',
    authDomain: 'nsysu-ap.firebaseapp.com',
    databaseURL: 'https://nsysu-ap.firebaseio.com',
    storageBucket: 'nsysu-ap.appspot.com',
    measurementId: 'G-FB2R468F3N',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDNF_8OFHvFgpKnKDfFnPR-2Cq_QobC08c',
    appId: '1:183269888565:web:eb8c3643b798655573577c',
    messagingSenderId: '183269888565',
    projectId: 'nsysu-ap',
    authDomain: 'nsysu-ap.firebaseapp.com',
    databaseURL: 'https://nsysu-ap.firebaseio.com',
    storageBucket: 'nsysu-ap.appspot.com',
    measurementId: 'G-5D6YPFX2PL',
  );
}