name: Store CD

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  flutter_version: '3.38.10'
  java_version: '17'
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  actions: write

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      version_code: ${{ steps.get_version_code.outputs.version_code }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: //' | cut -d'+' -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
      - name: Get version code from pubspec.yaml
        id: get_version_code
        run: |
          VERSION_CODE=$(grep '^version: ' pubspec.yaml | sed 's/version: //' | cut -d'+' -f2)
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
          echo "Version code: $VERSION_CODE"

  deploy_android:
    name: Android Play Store
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.java_version }}
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          KEYS_SECRET_PASSPHRASE: ${{ secrets.KEYS_SECRET_PASSPHRASE }}
      - name: Format changelog for Android
        run: bash "$GITHUB_WORKSPACE/.github/scripts/format_changelog.sh" ${{ needs.prepare.outputs.version_code }} android
        working-directory: ./android/fastlane
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Decrypt dev configs
        run: sh ./scripts/decrypt_dev_configs.sh
        env:
          DEV_CONFIGS_PASSPHRASE: ${{ secrets.DEV_CONFIGS_PASSPHRASE }}
      - name: Install Flutter dependencies
        run: flutter pub get
      - run: flutter build appbundle --release --build-number=${{ needs.prepare.outputs.version_code }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install Fastlane
        run: gem install fastlane fastlane-plugin-flutter_version
        working-directory: ./android
      - name: Run Fastlane
        run: fastlane playstore
        working-directory: ./android

  deploy_ios:
    name: iOS Deploy TestFlight
    needs: prepare
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.java_version }}
      - name: Format changelog for iOS
        run: bash "$GITHUB_WORKSPACE/.github/scripts/format_changelog.sh" ${{ needs.prepare.outputs.version_code }} ios
        working-directory: ./ios/fastlane
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Flutter Initialize
        run: |
          flutter doctor -v
          flutter clean
          dart pub global activate flutterfire_cli 1.1.0
      - name: Decrypt dev configs
        run: sh ./scripts/decrypt_dev_configs.sh
        env:
          DEV_CONFIGS_PASSPHRASE: ${{ secrets.DEV_CONFIGS_PASSPHRASE }}
      - run: flutter build ipa --release --build-number=${{ needs.prepare.outputs.version_code }}
      - name: Zip dSYM
        run: zip Runner.app.dSYM.zip -r ../archive/Runner.xcarchive/dSYMs/
        working-directory: ./build/ios/ipa
      - name: Decode API Key
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" | base64 --decode > ios/AuthKey.p8
      - name: Deploy iOS Beta to TestFlight via Fastlane
        run: fastlane ios release key_id:"${{ env.KEY_ID }}" issuer_id:"${{ env.ISSUER_ID }}"
        working-directory: ./ios
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          APP_STORE_CONNECT_APPLE_ID: '${{ secrets.APP_STORE_CONNECT_APPLE_ID }}'
          APP_STORE_CONNECT_BUNDLE_IDENTIFIER: '${{ secrets.APP_STORE_CONNECT_BUNDLE_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          KEY_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}'
          ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_API_API_ISSUER_ID }}'

  deploy_windows:
    name: Windows App
    needs: prepare
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Decrypt dev configs
        run: sh ./scripts/decrypt_dev_configs.sh
        env:
          DEV_CONFIGS_PASSPHRASE: ${{ secrets.DEV_CONFIGS_PASSPHRASE }}
      - name: Enable windows
        run: flutter config --enable-windows-desktop
      - run: flutter doctor -v
      - run: flutter pub get
      - name: Build windows
        run: flutter build windows --release --build-number=${{ needs.prepare.outputs.version_code }}
      - name: Zip files
        run: powershell Compress-Archive build\windows\x64\runner\Release\ windows.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: windows.zip

  github_release:
    name: Create GitHub Release
    needs: [prepare, deploy_android, deploy_ios, deploy_windows]
    if: always() && needs.prepare.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Format changelog for GitHub Release
        run: bash "$GITHUB_WORKSPACE/.github/scripts/format_changelog.sh" ${{ needs.prepare.outputs.version_code }} github
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-artifact
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: v${{ needs.prepare.outputs.version }}
          body_path: RELEASE_NOTE.md
          draft: false
          prerelease: false
          files: windows.zip
