name: Build Test

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
      -
  pull_request:
    branches:
      - master

jobs:

  build_android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          KEYS_SECRET_PASSPHRASE: ${{ secrets.KEYS_SECRET_PASSPHRASE }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.x'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Decrypt dev configs
        run: sh ./scripts/decrypt_dev_configs.sh
        env:
          DEV_CONFIGS_PASSPHRASE: ${{ secrets.DEV_CONFIGS_PASSPHRASE }}
      - name: Upgrades flutter
        run: flutter upgrade
      - run: flutter pub get
      - name: Build Android app bundle
        run: flutter build appbundle --release

  build_ios:
    name: Build iOS App
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.x'
          channel: 'stable'
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Flutter Initiaize
        run: |
            flutter doctor -v
            flutter clean
            dart pub global activate flutterfire_cli 1.1.0
      - name: Decrypt dev configs
        run: sh ./scripts/decrypt_dev_configs.sh
        env:
          DEV_CONFIGS_PASSPHRASE: ${{ secrets.DEV_CONFIGS_PASSPHRASE }}
      - run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign

  build_web:
    name: Build Web App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.x'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Decrypt dev configs
        run: sh ./scripts/decrypt_dev_configs.sh
        env:
          DEV_CONFIGS_PASSPHRASE: ${{ secrets.DEV_CONFIGS_PASSPHRASE }}
      - name: Upgrades flutter
        run: flutter upgrade
      - name: Enable Web
        run: flutter config --enable-web
      - run: flutter pub get
      - name: Build Web
        run: flutter build web

#  build_macos:
#    name: Build macOS App
#    runs-on: macOS-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Run Flutter tasks
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.29.x'
#          channel: 'stable'
#      - name: Decrypt dev configs
#        run: sh ./scripts/decrypt_dev_configs.sh
#        env:
#          DEV_CONFIGS_PASSPHRASE: ${{ secrets.DEV_CONFIGS_PASSPHRASE }}
#      - name: Upgrades flutter
#        run: flutter upgrade
#      - name: Enable macOS
#        run: flutter config --enable-macos-desktop
#      - run: flutter pub get
#      - name: Build macOS
#        run: flutter build macos --release
# TODO: comment for release not usage
#  build_linux:
#    name: Build Linux App
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Run Flutter tasks
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.29.x'
#          channel: 'stable'
#          cache: true
#          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
#      - name: Decrypt dev configs
#        run: sh ./scripts/decrypt_dev_configs.sh
#        env:
#          DEV_CONFIGS_PASSPHRASE: ${{ secrets.DEV_CONFIGS_PASSPHRASE }}
#      - name: Get new source_list
#        run: git clone https://github.com/Yukimura0119/source_list.git
#      - name: Copy to /etc/apt/sources.list
#        run: sudo cp -f source_list/sources.list /etc/apt/sources.list
#      - name: Update apt
#        run: sudo apt update
#      - name: Intall requird Dependencies
#        run: sudo apt --fix-broken -y install ninja-build libgtk-3-dev libblkid-dev libwebkit2gtk-4.0-dev
#      - name: Upgrades flutter
#        run: flutter upgrade
#      - name: Enable linux
#        run: flutter config --enable-linux-desktop
#      - run: flutter doctor -v
#      - run: flutter pub get
#      - name: Build linux
#        run: flutter build linux --release

  build_windows:
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.x'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Decrypt dev configs
        run: sh ./scripts/decrypt_dev_configs.sh
        env:
          DEV_CONFIGS_PASSPHRASE: ${{ secrets.DEV_CONFIGS_PASSPHRASE }}
      - name: Upgrades flutter
        run: flutter upgrade
      - name: Enable windows
        run: flutter config --enable-windows-desktop
      - run: flutter doctor -v
      - run: flutter pub get
      - name: Build windows
        run: flutter build windows --release
